"""
db/models.py
============
SQLAlchemy ORM models for LLM Cost Autopilot (Phase 4).

These models mirror ``db/schema.sql`` exactly.  If you modify one, update
the other.  The SQL file is used for initial setup; these models are used
by application code for all reads and writes.

Usage
-----
    from db.models import Base, RequestLog, VerificationLog
    from db.engine import get_engine

    async with get_engine().begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
"""
from __future__ import annotations

import pathlib
import sys
from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    NUMERIC,
    Boolean,
    ForeignKey,
    Index,
    Integer,
    Text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import TIMESTAMP

_PROJECT_ROOT = pathlib.Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))


# ---------------------------------------------------------------------------
# Base
# ---------------------------------------------------------------------------

class Base(DeclarativeBase):
    """SQLAlchemy declarative base for all ORM models."""
    pass


# ---------------------------------------------------------------------------
# RequestLog
# ---------------------------------------------------------------------------

class RequestLog(Base):
    """One row per LLM request dispatched by the router.

    Populated by ``db.logger.log_request()``.

    Attributes:
        request_id: UUID string — primary key, generated by the router.
        timestamp: UTC datetime when the request was dispatched.
        prompt_text: The original user prompt (full text).
        complexity_tier: Phase 2 classifier output ("simple"/"moderate"/"complex").
        model_id_used: The model_id that handled this request.
        provider: Short provider name (openrouter/groq/gemini/mistral/ollama).
        input_tokens: Provider-reported prompt token count.
        output_tokens: Provider-reported completion token count.
        cost_usd: Estimated USD cost (Decimal for precision).
        latency_ms: End-to-end wall-clock latency in milliseconds.
        verification: Back-reference to VerificationLog (optional, 1:1).
    """

    __tablename__ = "request_log"

    request_id: Mapped[str] = mapped_column(Text, primary_key=True)
    timestamp: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False
    )
    prompt_text: Mapped[str] = mapped_column(Text, nullable=False)
    complexity_tier: Mapped[str] = mapped_column(Text, nullable=False)
    model_id_used: Mapped[str] = mapped_column(Text, nullable=False)
    provider: Mapped[str] = mapped_column(Text, nullable=False)
    input_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    output_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    cost_usd: Mapped[Decimal] = mapped_column(NUMERIC(18, 10), nullable=False, default=0)
    latency_ms: Mapped[Decimal] = mapped_column(NUMERIC(12, 3), nullable=False, default=0)

    # 1:1 back-reference — optional (not every request gets verified)
    verification: Mapped["VerificationLog | None"] = relationship(
        "VerificationLog",
        back_populates="request",
        uselist=False,
        cascade="all, delete-orphan",
    )

    __table_args__ = (
        Index("idx_request_log_timestamp", "timestamp"),
        Index("idx_request_log_tier", "complexity_tier"),
        Index("idx_request_log_model", "model_id_used"),
    )

    def __repr__(self) -> str:
        return (
            f"<RequestLog request_id={self.request_id!r} "
            f"tier={self.complexity_tier!r} model={self.model_id_used!r} "
            f"cost=${float(self.cost_usd):.6f}>"
        )


# ---------------------------------------------------------------------------
# VerificationLog
# ---------------------------------------------------------------------------

class VerificationLog(Base):
    """One row per Phase 3 quality-verification check.

    Populated by ``db.logger.log_verification()``.
    Has a foreign-key relationship to ``request_log``.

    Attributes:
        request_id: Foreign key to ``request_log.request_id``.
        timestamp: UTC datetime when verification completed.
        reference_model_id: The high-quality model used for comparison.
        quality_score: LLM-judge score 0.0–1.0.
        passed: True if quality_score >= threshold.
        escalated: True if the reference response replaced the cheap answer.
        judge_justification: One-sentence explanation from the judge model.
        request: ORM back-reference to the parent RequestLog.
    """

    __tablename__ = "verification_log"

    request_id: Mapped[str] = mapped_column(
        Text,
        ForeignKey("request_log.request_id", ondelete="CASCADE"),
        primary_key=True,
    )
    timestamp: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False
    )
    reference_model_id: Mapped[str] = mapped_column(Text, nullable=False)
    quality_score: Mapped[Decimal] = mapped_column(NUMERIC(5, 4), nullable=False)
    passed: Mapped[bool] = mapped_column(Boolean, nullable=False)
    escalated: Mapped[bool] = mapped_column(Boolean, nullable=False)
    judge_justification: Mapped[str] = mapped_column(Text, nullable=False, default="")

    request: Mapped["RequestLog"] = relationship(
        "RequestLog", back_populates="verification"
    )

    __table_args__ = (
        Index("idx_verification_log_timestamp", "timestamp"),
        Index("idx_verification_log_passed", "passed"),
        Index("idx_verification_log_escalated", "escalated"),
    )

    def __repr__(self) -> str:
        return (
            f"<VerificationLog request_id={self.request_id!r} "
            f"score={float(self.quality_score):.3f} passed={self.passed} "
            f"escalated={self.escalated}>"
        )
